version: 2.1
orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  btd:
    jobs:
      - orb-tools/pack:
          source-dir: src/orb.yml
          destination-orb-path: ./orb/orb.yml
          workspace-path: ./orb
      - orb-tools/publish:
          attach-workspace: true
          orb-path: ./orb.yml
          orb-ref: yaradigitallabs/contrast-verify@dev:${CIRCLE_BRANCH}
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true
      - orb-tools/increment:
          attach-workspace: true
          orb-path: ./orb.yml
          orb-ref: yaradigitallabs/contrast-verify
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          segment: patch
